#!/bin/sh

ID="$(xinput list | grep -Eio 'touchpad\s*id=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}')"

ENABLED="$(xinput list-props $ID | awk '/\s*Device Enabled/ {print $4}')"

case $ENABLED in
    0) 
        xinput enable $ID
        CHANGE="enabled"
        ;;
    1)
        xinput disable $ID
        CHANGE="disabled"
        ;;
esac

notify-send -t 5000 "Touchpad $CHANGE."
